# Site settings
title: Liga Acadêmica de Urgência, Trauma e Emergência
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Universidade de São João del Rei
description: "Liga Acadêmica de Urgência, Trauma e Emergência da Universidade de São João del Rei"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  Liga Acadêmica
facebook_username:  lauteufsj
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
